### ISSUE TITLE
N/A

### ISSUE THREAD

**Issue by LeventHAN** [WarmonSD/armaturk#2]
### N/A

**Comment by WarmonSD** [comment]
Yakında Tüm Dosyalar Gelicektir Hocam Ordan Bakarsın :) Daha Neler Çalmışlar Desteğin İçin Teşekürler

**Comment by WarmonSD** [comment]
hocam sitende sadece github linki ni Koyabilirim İstersen

**Comment by SalihF7** [comment]
@LeventHAN o kadar alçaksınız ki cevap vermek bile istemedim bunu toplayarak yaptın ben yaptım diye atılıyorsun.

https://github.com/rumangerst/Black-Lagoon-Altis-Life/blob/master/MISSION/Altis_Life.Altis/core/functions/fn_onPlayerDisconnect.sqf
https://wiki.nitrado.net/de/Fix_Waffen_Drop_in_Altis_Life

> Çok laf bol yalan..

**Comment by SalihF7** [comment]
https://www.youtube.com/watch?v=-SpmKqJz_Us&feature=youtu.be Şunu buraya bırakır ve karakterini izle derim. @LeventHAN

**Comment by LeventHAN** [comment]
Ya siz beni bu ise sokmaya calisiyonuzda oyle 1 SSle olmaz yalniz
Neyse kanala cevabimi yazdim - yedeginide aldim silerseniz videoyu diye.
Bak simdi o video nasil silincek 1 haftaya - beni haksizyere sokmak neymis goruceksiniz o kanaldan tut sunucunuza kadar gidicem nasil iftira atilirmis sonuclari neymis catur cutur katlanicaksiniz kanit olarakta o videonuzu kullanicam yine - saolun...
